# Wine clustering
* 아래 와인 데이터를 이용하여 와인을 클러스터링하고 보고서를 작성하세요.
* 코드, 클러스터링 결과, 보고서를 종합적으로 평가합니다. 
* 다음 사이트의 다양한 클러스터링 기법을 참조하세요.
* https://scikit-learn.org/stable/modules/clustering.html

범주의 다양한 변수를 처리할 수 있는 k-mode clustering을 사용했습니다

In [ ]:
from sklearn.datasets import load_wine
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
from sklearn.metrics import silhouette_score
import sklearn.metrics as metrics


wine = load_wine()
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [ ]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

feature_names
 
  0: 'alcohol'

  1: 'malic_acid'
 
  2: 'ash'
 
  3: 'alcalinity_of_ash'
 
  4: 'magnesium'
 
  5: 'total_phenols'
 
  6: 'flavanoids'
 
  7: 'nonflavanoid_phenols'
 
  8: 'proanthocyanins'
 
  9: 'color_intensity'
 
  10: 'hue'
 
  11:'od280/od315_of_diluted_wines'
 
  12: 'proline'

In [ ]:
X=wine['data']
y=wine['target']

In [ ]:
df.describe()


0           1           2   ...          10          11           12
count  178.000000  178.000000  178.000000  ...  178.000000  178.000000   178.000000
mean    13.000618    2.336348    2.366517  ...    0.957449    2.611685   746.893258
std      0.811827    1.117146    0.274344  ...    0.228572    0.709990   314.907474
min     11.030000    0.740000    1.360000  ...    0.480000    1.270000   278.000000
25%     12.362500    1.602500    2.210000  ...    0.782500    1.937500   500.500000
50%     13.050000    1.865000    2.360000  ...    0.965000    2.780000   673.500000
75%     13.677500    3.082500    2.557500  ...    1.120000    3.170000   985.000000
max     14.830000    5.800000    3.230000  ...    1.710000    4.000000  1680.000000

[8 rows x 13 columns]

In [ ]:
df.columns

RangeIndex(start=0, stop=13, step=1)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       178 non-null    float64
 1   1       178 non-null    float64
 2   2       178 non-null    float64
 3   3       178 non-null    float64
 4   4       178 non-null    float64
 5   5       178 non-null    float64
 6   6       178 non-null    float64
 7   7       178 non-null    float64
 8   8       178 non-null    float64
 9   9       178 non-null    float64
 10  10      178 non-null    float64
 11  11      178 non-null    float64
 12  12      178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB


null 데이터 없음!

In [ ]:
df=pd.DataFrame(X)

In [ ]:
df2=pd.DataFrame(y)

In [ ]:
df

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [ ]:
km = KModes(n_clusters=3, init = "Huang", n_init = 1, verbose=1)
fitClusters = km.fit_predict(df)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 12, cost: 2122.0
Run 1, iteration: 2/100, moves: 1, cost: 2122.0


In [ ]:
fitClusters

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1,
       0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 2, 0, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0,
       0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 2, 0,
       1, 1], dtype=uint16)

In [ ]:
score = metrics.accuracy_score(y,fitClusters)
print('Accuracy:{0:f}'.format(score))

Accuracy:0.393258


In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters = 3, verbose=1)
clusters=kmeans.fit(df, y)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2421402.394751805
start iteration
done sorting
end inner loop
Iteration 1, inertia 2376432.0072191856
start iteration
done sorting
end inner loop
Iteration 2, inertia 2370689.686782968
start iteration
done sorting
end inner loop
Iteration 3, inertia 2370689.686782968
center shift 0.000000e+00 within tolerance 7.602548e-01
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2390778.2593590356
start iteration
done sorting
end inner loop
Iteration 1, inertia 2371841.591551583
start iteration
done sorting
end inner loop
Iteration 2, inertia 2370689.686782968
start iteration
done sorting
end inner loop
Iteration 3, inertia 2370689.686782968
center shift 0.000000e+00 within tolerance 7.602548e-01
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2969326.2278954666
start iteration
done sorting
end inner loop
Iteration 1, inertia 2

In [ ]:
kme=kmeans.predict(df)

In [ ]:
fitClusters2 = km.fit_predict(df)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 15, cost: 2131.0
Run 1, iteration: 2/100, moves: 7, cost: 2127.0
Run 1, iteration: 3/100, moves: 1, cost: 2127.0


In [ ]:
fitClusters2

array([0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 1, 0, 2, 0, 1, 0, 2, 2, 0, 1, 2, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 1, 1, 2, 0, 2, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0], dtype=uint16)

In [ ]:
from collections import Counter
print(Counter(fitClusters2),
Counter(fitClusters))

Counter({0: 131, 1: 24, 2: 23}) Counter({0: 121, 1: 32, 2: 25})


In [ ]:
score = metrics.accuracy_score(y,fitClusters2)
print('Accuracy:{0:f}'.format(score))

Accuracy:0.370787


계층적 범주의 다양한 변수를 처리할 수 있는 k-modes 군집화는 k-means군집화보다 높은 정확도을 보였습니다.